### PR TITLE
In 689 fix 1000 file breakage

### LINKED ISSUE #6: Fails if >1000 files present
Fails if >1000 files present in GS_projects due to 1000 files limit on dx ua.

### PR DESCRIPTION
**Pull request by spaul91**
Added functionality where the script will move uploaded data to an archive directory that the user sets in the config file. Fixes #6

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9)

### CODE REVIEW

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[`iscan_to_dnanexus/iscan_upload.sh` line 1 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9#-O2_IJfM2QnfCp9BYzGs:-O2_IJfM2QnfCp9BYzGt:b-9okjy3) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/9e3ce5b201bf14f5497aa0189d19f96c424b0359/iscan_to_dnanexus/iscan_upload.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Sorry, why are there 2 copies of 'iscan_upload.sh' at different file levels? I see they are slightly different, one matches on *_GS and the other matches on ${CONFIG[ISCAN_DIR]}/*_GS. Is this a Reviewable error?

**Comment by spaul91** [comment]
*[`iscan_to_dnanexus/iscan_upload.sh` line 1 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9#-O2_IJfM2QnfCp9BYzGs:-O338rZI6y6APOP9uLAs:b-365ih0) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/9e3ce5b201bf14f5497aa0189d19f96c424b0359/iscan_to_dnanexus/iscan_upload.sh#L1)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Sorry, why are there 2 copies of 'iscan_upload.sh' at different file levels? I see they are slightly different, one matches on *_GS and the other matches on ${CONFIG[ISCAN_DIR]}/*_GS. Is this a Reviewable error?
</blockquote></details>

oops. yeah that was a mistake, I've cleaned it up now. The top-level directory contains the right script now

**Comment by spaul91** [comment]
*[`iscan_to_dnanexus/iscan_upload.sh` line 1 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9#-O2_IJfM2QnfCp9BYzGs:-O339iH90j4U7nEuRvQz:bv93t4g) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/9e3ce5b201bf14f5497aa0189d19f96c424b0359/iscan_to_dnanexus/iscan_upload.sh#L1)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

oops. yeah that was a mistake, I've cleaned it up now. The top-level directory contains the right script now
</blockquote></details>

and there's only one of each file, etc.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`iscan_upload.sh` line 34 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9#-O336IT13Sc3mhaL_apP:-O336IT21N0PByDfoKfK:b-nmexhj) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/9e3ce5b201bf14f5497aa0189d19f96c424b0359/iscan_upload.sh#L34)):*
> ```Shell
>     mkdir -p ${CONFIG[ARCHIVE_DIR]}/${DATA_SUBDIR}
>     mv ${CONFIG[ISCAN_DIR]}/${DATA_SUBDIR}/* ${CONFIG[ARCHIVE_DIR]}/${DATA_SUBDIR}/
> done
> ```

If an ua upload fails, will the data directory still be moved to the archive dir despite the data not being in dx?



_Code quote:_
```Shell
for DATA_SUBDIR in GS_*; do
    ${CONFIG[UPLOAD_AGENT_PATH]}/ua \
        --auth-token $(cat ${CONFIG[AUTH_TOKEN_PATH]}) \
        --recursive \
        --project=${CONFIG[DX_PROJECT_ID]} \
        ${CONFIG[ISCAN_DIR]}/${DATA_SUBDIR}
done

# move all to archive
for DATA_SUBDIR in GS_*; do
    # make it if it doesn't exist
    mkdir -p ${CONFIG[ARCHIVE_DIR]}/${DATA_SUBDIR}
    mv ${CONFIG[ISCAN_DIR]}/${DATA_SUBDIR}/* ${CONFIG[ARCHIVE_DIR]}/${DATA_SUBDIR}/
done
```

**Review by corbin-chris — APPROVED** [review]
All OK, need to address Matt's comments before merge.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9#-:-O3WrlqS7uSrPodyRfzK:be6qmi8)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

**Comment by spaul91** [comment]
*[`iscan_upload.sh` line 34 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9#-O336IT13Sc3mhaL_apP:-O3XvD8x8NOKE2gvCm21:b-6pnb4a) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/9e3ce5b201bf14f5497aa0189d19f96c424b0359/iscan_upload.sh#L34)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

If an ua upload fails, will the data directory still be moved to the archive dir despite the data not being in dx?
</blockquote></details>

Yes. A workaround would be to go into the archive directory and move it back to the upload area. Would you like me to try to add error handling for this?

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[`iscan_upload.sh` line 34 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/9#-O336IT13Sc3mhaL_apP:-O3aca5PCOA6ko1PXiix:b-azmqlg) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/9e3ce5b201bf14f5497aa0189d19f96c424b0359/iscan_upload.sh#L34)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Yes. A workaround would be to go into the archive directory and move it back to the upload area. Would you like me to try to add error handling for this?
</blockquote></details>

Yes please, I think it's necessary to handle this.

**Pull request closed without merging**
