### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by spaul91**
- Config file compatibility added; allows external settings of:
    - DNANexus API token
    - iScan data directory
    - Upload Agent directory
    - Target DNANexus project
- iScan data subdirectory generalised; any data under a directory with prefix GS_* will be uploaded

Please see https://cuhbioinformatics.atlassian.net/wiki/spaces/INF/pages/3198288515/Testing+iscan+upload.sh+v2.0.0 for testing details. Thank you

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: all files reviewed, 2 unresolved discussions (waiting on @spaul91)

___
*[`iscan_upload.sh` line 3 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsNB183xWGcNhqf-aE:-NwsNB183xWGcNhqf-aF:b-5m816g) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> typeset -A CONFIG
> ```

looks like typeset is obsolete: https://unix.stackexchange.com/a/66009
___
*[`iscan_upload.sh` line 18 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQm0YBqdOzhBQ0POs:-NwsQm0ZCDfHJlaNGPgx:b-cpy9om) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L18)):*
> ```Shell
>         CONFIG[$VARNAME]=$(echo "$LINE" | cut -d '=' -f 2-)
>     fi
> done < $ISCAN_CONFIG_PATH 
> ```

am i being dumb or is that variable never declared?

**Comment by spaul91** [comment]
*[`iscan_upload.sh` line 18 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQm0YBqdOzhBQ0POs:-NwsSc3w7NPCLP6SWs5j:b64xbn3) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L18)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

am i being dumb or is that variable never declared?
</blockquote></details>

Not at all. You're supposed to set it with `export` before running the script. The README needs to be updated, good spot :)

**Comment by spaul91** [comment]
*[`iscan_upload.sh` line 3 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsNB183xWGcNhqf-aE:-NwsSzj80PhQ7oirtoB1:b-x924vf) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L3)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

looks like typeset is obsolete: https://unix.stackexchange.com/a/66009
</blockquote></details>

If I replaced this with `declare` would I need to redo all the test documentation? I would like to change it but it could be an admin headache

**Review by corbin-chris — CHANGES_REQUESTED** [review]
Just looked at the non-bash bits so far, as someone else got those in the meantime

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-:-NwsTBve5S2BfHCbGI4s:btt6lak)* status: all files reviewed, 4 unresolved discussions (waiting on @spaul91 and @Yu-jinKim)

___
*[`iscan_upload.conf` line 4 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQwQ0Ewgjz1vXU3ES:-NwsQwQ0Ewgjz1vXU3ET:b-yquzgb) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.conf#L4)):*
> ```
> ISCAN_DIR=
> UPLOAD_AGENT_PATH=
> DX_PROJECT_ID=
> ```

Could you please add *.conf and iscan_upload.conf files (and variants thereof) to gitignore? And rename this file to something like 'example_iscan_upload.conf'?
The purpose of this is to discourage people from adding information from 'iscan_upload.conf' and accidentally committing it, by forcing them to make a new file which is on the ignore list.
___
*[`README.md` line 13 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsS2iSCWDV_64ow2F3:-NwsS2iSCWDV_64ow2F4:bejgt2t) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/README.md#L13)):*
> ```Markdown
> 
> ## What data are required for this app to run?
> iScan data and api token must be available (with appropriate permissions) on the local server
> ```

Could you please add here that a config file must be made and populated?

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: all files reviewed, 4 unresolved discussions (waiting on @spaul91 and @Yu-jinKim)

___
*[`iscan_upload.sh` line 18 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQm0YBqdOzhBQ0POs:-NwsTI9u3W4MP1j7kTE_:b-b3wizd) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L18)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Not at all. You're supposed to set it with `export` before running the script. The README needs to be updated, good spot :)
</blockquote></details>

might want to have a check for ISCAN_CONFIG_PATH and exit if the variable is undefined or not exported before running this script

**Comment by spaul91** [comment]
*[`README.md` line 13 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsS2iSCWDV_64ow2F3:-NwsTMPM1RQcHLkb5stf:b-qdypii) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/README.md#L13)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you please add here that a config file must be made and populated?
</blockquote></details>

Sure :) README update incoming

**Comment by spaul91** [comment]
*[`iscan_upload.conf` line 4 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQwQ0Ewgjz1vXU3ES:-NwsTbop5tOlBxdFhr1X:b-inmlu) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.conf#L4)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you please add *.conf and iscan_upload.conf files (and variants thereof) to gitignore? And rename this file to something like 'example_iscan_upload.conf'?
The purpose of this is to discourage people from adding information from 'iscan_upload.conf' and accidentally committing it, by forcing them to make a new file which is on the ignore list.
</blockquote></details>

Yep will do thank you :)

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: all files reviewed, 5 unresolved discussions (waiting on @corbin-chris, @spaul91, and @Yu-jinKim)

___
*[`iscan_upload.sh` line 21 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsTUdO3rpcX2QnkIaG:-NwsTUdO3rpcX2QnkIaH:b-p4t6an) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L21)):*
> ```Shell
> 
> for DATA_SUBDIR in GS_*; do
>     ${CONFIG[UPLOAD_AGENT_PATH]}/ua \
> ```

will be good to have check if ua pathway is defined before running it

**Comment by spaul91** [comment]
*[`iscan_upload.sh` line 21 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsTUdO3rpcX2QnkIaG:-NwsTnLcARz5sZzUDuOn:ba8ywbo) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L21)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

will be good to have check if ua pathway is defined before running it
</blockquote></details>

If the `ua` path is undefined then the script will crash anyway. `ua` is an executable

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: all files reviewed, 4 unresolved discussions (waiting on @corbin-chris and @Yu-jinKim)

**Comment by spaul91** [comment]
*[`iscan_upload.conf` line 4 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQwQ0Ewgjz1vXU3ES:-NwsmfrkEQk1fgIs2W3t:btvlvp7) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.conf#L4)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Yep will do thank you :)
</blockquote></details>

I should've realised this earlier, but the script accepts any filename where the config is passed in. Someone might not call it `.conf`, so is adding this to `.gitignore` going to prevent anything?

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @JasonLing95, @spaul91, and @Yu-jinKim)

___
*[`iscan_upload.conf` line 4 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQwQ0Ewgjz1vXU3ES:-Nwsnnnd-4kEhHARB4ku:b-xrqv27) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.conf#L4)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I should've realised this earlier, but the script accepts any filename where the config is passed in. Someone might not call it `.conf`, so is adding this to `.gitignore` going to prevent anything?
</blockquote></details>

I didn't realise either. I'd accept any solution which encourages people to not commit paths to that example file. I see 2 routes, the first is faster and probably adequate, as people shouldn't be pushing from a deployment environment anyway:

1. Remove 'iscan_upload.conf' as a file entirely, and instead, just add a 'how to format the config file' in the README with a note not to commit their config.
2. Lock the script down so that it only takes a file with a designated ending or name, and errors out otherwise.

Just something to make it easier for users to keep track of which files are important for what, in the deployment environment.

**Comment by spaul91** [comment]
*[`iscan_upload.conf` line 4 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsQwQ0Ewgjz1vXU3ES:-NwsqmL4-iojuWq2iXOS:b-ogunu0) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.conf#L4)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I didn't realise either. I'd accept any solution which encourages people to not commit paths to that example file. I see 2 routes, the first is faster and probably adequate, as people shouldn't be pushing from a deployment environment anyway:

1. Remove 'iscan_upload.conf' as a file entirely, and instead, just add a 'how to format the config file' in the README with a note not to commit their config.
2. Lock the script down so that it only takes a file with a designated ending or name, and errors out otherwise.

Just something to make it easier for users to keep track of which files are important for what, in the deployment environment.
</blockquote></details>

I've done the first one :)

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @spaul91)

___
*[`iscan_upload.sh` line 3 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsNB183xWGcNhqf-aE:-NwsyUI15GrAd9AsudnD:b-wvrdpd) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L3)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

If I replaced this with `declare` would I need to redo all the test documentation? I would like to change it but it could be an admin headache
</blockquote></details>

hum i'm not sure. If you want to hold off, could you open an issue so that it'd get pick up for a subsequent update?

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: all files reviewed, 3 unresolved discussions (waiting on @corbin-chris and @spaul91)

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: all files reviewed, 2 unresolved discussions (waiting on @spaul91)

___
*[`iscan_upload.sh` line 20 at r3](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwtWggM2tXGSa4SYwJ5:-NwtWggM2tXGSa4SYwJ6:b4e5pz4) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/f36c6e1f306c1acee103f6effd4d3b4c8471131e/iscan_upload.sh#L20)):*
> ```Shell
> done < $ISCAN_CONFIG_PATH 
> 
> for DATA_SUBDIR in GS_*; do
> ```

Do you need to prepend $ISCAN_CONFIG_PATH path to the GS_* files here? Where does the bash script assemble the list of subdirectory names to loop over and upload?

**Comment by spaul91** [comment]
*[`iscan_upload.sh` line 3 at r1](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwsNB183xWGcNhqf-aE:-NwtYond0y2TEXb2OAcI:b-ln761p) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/7845cfcc75e7d286815db04ff5299b9910e6d382/iscan_upload.sh#L3)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

hum i'm not sure. If you want to hold off, could you open an issue so that it'd get pick up for a subsequent update?
</blockquote></details>

That's a good idea. I'll open an issue and wait for feedback on the testing

**Comment by spaul91** [comment]
*[`iscan_upload.sh` line 20 at r3](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwtWggM2tXGSa4SYwJ5:-NwtYwPdDUGLH62tOLee:b-uez5pq) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/f36c6e1f306c1acee103f6effd4d3b4c8471131e/iscan_upload.sh#L20)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Do you need to prepend $ISCAN_CONFIG_PATH path to the GS_* files here? Where does the bash script assemble the list of subdirectory names to loop over and upload?
</blockquote></details>

The way it works is that `$ISCAN_DIR` is set by the user in the config file, and it's the parent directory where the iScan data subfolders live. The script gets the data location from `${CONFIG[ISCAN_DIR]}`, which you can see in L25. `${DATA_SUBDIR}` is expanded to the name of the iScan data directory being worked on at that moment.

iScan data subfolders invariably follow the `GS_*` naming convention (e.g., `GS_reports`, `GS_data` and so on), which is why there's a glob expansion happening in the `for DATA_SUBDIR etc` bit.

I hope I've explained that well

**Comment by spaul91** [comment]
*[`iscan_upload.sh` line 20 at r3](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7#-NwtWggM2tXGSa4SYwJ5:-NwtfGcp5Qg5xH-v-e76:b1aihc) ([raw file](https://github.com/eastgenomics/iscan_to_dnanexus/blob/f36c6e1f306c1acee103f6effd4d3b4c8471131e/iscan_upload.sh#L20)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

The way it works is that `$ISCAN_DIR` is set by the user in the config file, and it's the parent directory where the iScan data subfolders live. The script gets the data location from `${CONFIG[ISCAN_DIR]}`, which you can see in L25. `${DATA_SUBDIR}` is expanded to the name of the iScan data directory being worked on at that moment.

iScan data subfolders invariably follow the `GS_*` naming convention (e.g., `GS_reports`, `GS_data` and so on), which is why there's a glob expansion happening in the `for DATA_SUBDIR etc` bit.

I hope I've explained that well
</blockquote></details>

Sorry @corbin-chris , to answer your question more precisely, no, we don't need to prepend anything to `GS_*`.

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/iscan_to_dnanexus/7)* status: all files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

**Pull request merged**
